import type { ImageRequireSource } from "react-native";

// 材料の写真（assets/ingredients/thumbs）。assets/ingredients の写真から作ったもの。出典は assets/ingredients/CREDITS.md
export const INGREDIENT_PHOTOS: Partial<Record<string, ImageRequireSource>> = {
  "bread": require("../../../assets/ingredients/thumbs/bread.jpg"),
  "burdock": require("../../../assets/ingredients/thumbs/burdock.jpg"),
  "butter": require("../../../assets/ingredients/thumbs/butter.jpg"),
  "carrot": require("../../../assets/ingredients/thumbs/carrot.jpg"),
  "cheese": require("../../../assets/ingredients/thumbs/cheese.jpg"),
  "chicken-bouillon": require("../../../assets/ingredients/thumbs/chicken-bouillon.jpg"),
  "consomme": require("../../../assets/ingredients/thumbs/consomme.jpg"),
  "corn": require("../../../assets/ingredients/thumbs/corn.jpg"),
  "doubanjiang": require("../../../assets/ingredients/thumbs/doubanjiang.jpg"),
  "egg": require("../../../assets/ingredients/thumbs/egg.jpg"),
  "fresh-cream": require("../../../assets/ingredients/thumbs/fresh-cream.jpg"),
  "garlic-paste": require("../../../assets/ingredients/thumbs/garlic-paste.jpg"),
  "garlic": require("../../../assets/ingredients/thumbs/garlic.jpg"),
  "ginger-paste": require("../../../assets/ingredients/thumbs/ginger-paste.jpg"),
  "ginger": require("../../../assets/ingredients/thumbs/ginger.jpg"),
  "karashi": require("../../../assets/ingredients/thumbs/karashi.jpg"),
  "ketchup": require("../../../assets/ingredients/thumbs/ketchup.jpg"),
  "komatsuna": require("../../../assets/ingredients/thumbs/komatsuna.jpg"),
  "lotus-root": require("../../../assets/ingredients/thumbs/lotus-root.jpg"),
  "mackerel": require("../../../assets/ingredients/thumbs/mackerel.jpg"),
  "mayonnaise": require("../../../assets/ingredients/thumbs/mayonnaise.jpg"),
  "milk": require("../../../assets/ingredients/thumbs/milk.jpg"),
  "miso": require("../../../assets/ingredients/thumbs/miso.jpg"),
  "onion": require("../../../assets/ingredients/thumbs/onion.jpg"),
  "oyster-sauce": require("../../../assets/ingredients/thumbs/oyster-sauce.jpg"),
  "pork-belly": require("../../../assets/ingredients/thumbs/pork-belly.jpg"),
  "pork-loin": require("../../../assets/ingredients/thumbs/pork-loin.jpg"),
  "potato": require("../../../assets/ingredients/thumbs/potato.jpg"),
  "pumpkin": require("../../../assets/ingredients/thumbs/pumpkin.jpg"),
  "rice": require("../../../assets/ingredients/thumbs/rice.jpg"),
  "salad-oil": require("../../../assets/ingredients/thumbs/salad-oil.jpg"),
  "salmon": require("../../../assets/ingredients/thumbs/salmon.jpg"),
  "salt": require("../../../assets/ingredients/thumbs/salt.jpg"),
  "soy-sauce": require("../../../assets/ingredients/thumbs/soy-sauce.jpg"),
  "sugar": require("../../../assets/ingredients/thumbs/sugar.jpg"),
  "udon": require("../../../assets/ingredients/thumbs/udon.jpg"),
  "vinegar": require("../../../assets/ingredients/thumbs/vinegar.jpg"),
  "wasabi": require("../../../assets/ingredients/thumbs/wasabi.jpg"),
  "white-sesame": require("../../../assets/ingredients/thumbs/white-sesame.jpg"),
  "worcestershire-sauce": require("../../../assets/ingredients/thumbs/worcestershire-sauce.jpg"),
};
